import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useMemo, useState } from 'react'
import { useKey } from 'react-use'
import styled from 'styled-components'

const Container = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100vh;
  min-height: 100vh;
  padding: 0 0.5rem;
  background-color: black;
`

const Main = styled.main`
  display: flex;
  flex: 1;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 5rem 0;
`

const Grid = styled.div`
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: center;
  max-width: 500px;
  margin-top: 3rem;

  @media (max-width: 600px) {
    flex-direction: column;
    width: 100%;
  }
`
const Area = styled.div<{ val: number }>`
  width: 50px;
  height: 50px;
  border: 1px solid black;
  background-color: ${(props) => (props.val === 1 ? 'lightBlue' : 'gray')};
`

const Home: NextPage = () => {
  // Tetrisの特徴
  // 1.ある一定の時間がたったらブロックが投下される
  // 2.時間経過中は下り続ける
  // 3.１行うまったらクリアされる
  // 4.クリア行より上の行は１段さがる
  // 5.最上段より上にブロックが来たら負け
  // prettier-ignore
  const longRod: number[][] = [
    [1],
    [1],
    [1],
    [1]
  ]
  const square: number[][] = [
    [1, 1],
    [1, 1],
  ]
  const [timer, setTimer] = useState(0)
  const [blockHead, setBlockHead] = useState(0)
  const [currentParts, setCurrentParts] = useState([[0]])
  const [sidePoint, setSidePoint] = useState(4)
  const [saveParts, setSaveParts] = useState([{}])
  const moveLeft = () => setSidePoint((sidePoint) => --sidePoint)
  const moveRight = () => setSidePoint((sidePoint) => ++sidePoint)
  useKey('ArrowLeft', moveLeft)
  useKey('ArrowRight', moveRight)
  // prettier-ignore
  const [field, setField] = useState([
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  ])
  const partsDown = useMemo(() => {
    const addField = new Array(20)
    for (let y = 0; y < 20; y++) {
      addField[y] = new Array(10).fill(0)
    }
    for (let n = 0; n < currentParts.length; n++) {
      addField[n + blockHead][sidePoint] = 1
    }
    return addField
  }, [sidePoint])

  const partsPosition = useMemo(() => {
    const fieldData: number[] = partsDown.flat()
    const savePartsList = saveParts
    const idxList = []
    for (let i = 0; i < fieldData.length; i++) {
      if (fieldData[i] === 1) idxList.push(i)
    }
    for (const elm of idxList) {
      const exclusion = Math.floor(elm / 10)
      const surplus = elm % 10
      savePartsList.push({ x: exclusion, y: surplus })
    }
    return savePartsList
  }, [partsDown])

  const displayField = useMemo(() => {
    const pp = partsPosition
    // const newField: number[][] = JSON.parse(JSON.stringify(field))
    for (const elm of pp) {
      console.log(elm)
      // newField[elm.x][elm.y] = 1
    }
    return partsDown
  }, [timer])

  useEffect(() => {
    const timeoutId = setTimeout(() => {
      const time = timer + 1
      setTimer(time)
      setCurrentParts(longRod) // partsを切り替えていく
      setField(displayField)
      blockHead === 16 ? setBlockHead(0) : setBlockHead(blockHead + 1)
    }, 1000)
    return () => {
      clearTimeout(timeoutId)
    }
  }, [timer])
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Grid>
          {field.map((row, x) =>
            row.map((col, y) => (
              <Area key={`${x}-${y}`} val={field[x][y]}>
                {x}, {y}
              </Area>
            ))
          )}
        </Grid>
      </Main>
    </Container>
  )
}
export default Home
